version: "3.4"
services:
    documentdb:
        image: mongo:3.6
        networks:
            - functions
    service:
        image: fpommerening/spartakiade2018:poi-service
        networks:
            - functions
        secrets:
          - DocumentDBCnn
        environment:
          LETSENCRYPT_EMAIL: "frank@openfaas-dotnet.de"
          LETSENCRYPT_HOST: "poi.openfaas-dotnet.de"
          VIRTUAL_HOST: "poi.openfaas-dotnet.de"
          VIRTUAL_PORT: "8080"
        volumes: 
          - data:/data/db
        depends_on:
            - documentdb
secrets:
  DocumentDBCnn:
      external:
          name: PoIDBCnn
volumes:
  data:
    external:
      name: poi-data

          
networks:
  functions:
    external:
          name: functions